services:
  - type: web
    name: maharashtra-survey-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: BCRYPT_ROUNDS
        value: 12
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: maharashtra-survey-db
    databaseName: maharashtra_survey_db
    user: survey_user
    plan: free
