services:
  - type: web
    name: explorebackend
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: explorebackend-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://surveyapplication-gnqf21zjg-vijay-vs-projects-ebeee0fa.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: BCRYPT_ROUNDS
        value: 12

databases:
  - name: maharashtra-survey-db
    databaseName: maharashtra_survey_db
    user: survey_user
    plan: free
