name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render service
        run: curl -s https://explorebackend-qy7b.onrender.com/health > /dev/null
